export enum BookGenre {
    ROMANCE = "ROMANCE",
    MYSTERY = "MYSTERY",
    FANTASY = "FANTASY",
    SCIENCE_FICTION = "SCIENCE FICTION",
    THRILLER = "THRILLER",
    HORROR = "HORROR",
    RELIGIOUS = "RELIGIOUS",
    BIOGRAPHY = "BIOGRAPHY",
    KIDS = "KIDS",
    NOVEL = "NOVEL",
}